language: node_js
node_js: 10

matrix:
  include:
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.59.x
    install:
    - ./scripts/install.ios.sh
    script:
    - ./scripts/ci.ios.sh
    - ./scripts/upload_artifact.sh
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.58.x
    install:
    - ./scripts/install.ios.sh
    script:
    - ./scripts/ci.ios.sh
    - ./scripts/upload_artifact.sh
  - language: android
    env:
    - REACT_NATIVE_VERSION=0.59.x
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      - sys-img-x86-android-26
      - sys-img-x86-android-28
      - ndk-bundle
      licenses:
      - ndk-bundle
    install:
    - ./scripts/install.android.sh
    script:
    - export ANDROID_NDK="$ANDROID_HOME/ndk-bundle"
    - ./scripts/ci.android.sh
  # Example Projects
  - language: objective-c
    os: osx
    osx_image: xcode10.2
    env:
    - REACT_NATIVE_VERSION=0.59.x
    install:
    - ./scripts/install.ios.sh
    script:
    - ./scripts/demo-projects.ios.sh

branches:
  only:
  - travis_integration
  - master
before_install:
- nvm install 10
- pip install awscli --upgrade --user
notifications:
  email: true
  slack:
    secure: ExAwGcI4WlRoi/F2AKMds2eNQZ90susGT2k/CSU1ZQdTL5jaeMW6/i86Uz6Goilnd7qL/1GhlHF9Q48yYtctLVg4zSKH3uclHDDtPfWsF/R7+UWBPYtvhuW2VvL4ota8b0QzUlTz3iS0G3iD4AFqnAZUgYqjSeF1arv+YKOTEXzGyPtj3xjD9TSSjamnSEgGd18RRKpG8FWQr631yOSucikUsYcetV8bUTs6PtjcIC0XK1d1Nv/eMJxSwTQCAptQbxPTO0FBEEH+lQ6H5oQ7mvyNQ7BBUEunUWkUsCh85SsqHLbnCaiPojmI8ICUJBDNSDvzvyt1JJOxnjWtXlLu5xLOQRYeMvr9p66uBMTxTw2LXagSw4bxAf8LHXK/EOssTv+bE6gujNga0FF3jOLTDUZF93OT7TCsrVQrIkiKBl/YoJVc137dz/fUz3wA/JkmqQIV0i9BMUVNYlBGg3J9Omo8nQXTEvqNpYdSfWEm6cZT73kRrdiuittcBXUeWaTkqThmL8KMO5u+InUQhOhhxMmZ/u3DZRTxtHu9ndOdMrWaOmDj4MXpTsml6qelFHMdQoNQubUgdpSb0H0KvGObnQwFR3V2alPT6Ovx1e+XzjBiV2CNP3jHci52JGAlPtGRxctiXUYL9TZYgpJdO/IxJR/lAhA7ZJLsfHGL4LUF65o=
